# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2

commands:
  configure_npm:
    description: "Configure the npm client to use Agora"
    steps:
      - run: npm config set _auth $NPM_AUTH
      - run: npm config set email $NPM_EMAIL
      - run: npm config set always-auth true
      - run: npm config set registry https://agora.dequecloud.com/artifactory/api/npm/dequelabs/

defaults: &defaults
  docker:
      - image: circleci/node:12.14.1
    working_directory: ~/project/csd

jobs:
  build:
    <<: *defaults
    

    steps:
      - checkout:
          path: ~/project

      - restore_cache: 
          keys: 
            - v1-repo-{{ checksum "package-lock.json" }}
          
      - run:
          name: Install dependencies with NPM
          command: npm ci # replace with `yarn install` if using yarn
            # path: ~/project/csd/node_modules
      
      # - save_cache: # special step to save the dependency cache
      #     key: v1-repo-{{ checksum "package-lock.json" }}
      #     paths:
      #       - "node_modules"

      # - run:
      #     name: Run tests
      #     # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
      #     command: yarn test # replace with `yarn test` if using yarn

workflows:
  version: 2
  Build and Test:
    jobs:
      - build