# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    working_directory: ~/project/csd

    steps:
      - checkout:
          path: ~/project
      
      - run:
          name: check working directory
          command: pwd

      - run:
          name: check contents
          command: ls

      # - run:
      #     name: check inner contents
      #     command: ls ./csd

      # - restore_cache: 
      #     keys: 
      #       - v1-repo-{{ checksum "./csd/package-lock.json" }}
          

      # - run:
      #     name: Install dependencies with NPM
      #     command: npm install # replace with `yarn install` if using yarn
      
      # - save_cache: # special step to save the dependency cache
      #     key: v1-repo-{{ checksum "package-lock.json" }}
      #     paths:
      #       - "node_modules"

      # - run:
      #     name: Run tests
      #     # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
      #     command: yarn test # replace with `yarn test` if using yarn

workflows:
  version: 2
  Build and Test:
    jobs:
      - build